import { describe, it, expect } from 'vitest';
import { generateShortCode, SHORT_CODE_LENGTH, ShortCode, isValidShortCode } from '../../src/lib/shortcode';

describe('shortcode', () => {
  describe('SHORT_CODE_LENGTH', () => {
    it('should be 7', () => {
      expect(SHORT_CODE_LENGTH).toBe(7);
    });
  });

  describe('ShortCode type', () => {
    it('should be assignable from generateShortCode return value', () => {
      const code: ShortCode = generateShortCode();
      expect(typeof code).toBe('string');
    });
  });

  describe('generateShortCode', () => {
    it('should return a string of exactly 7 characters', () => {
      const code = generateShortCode();
      expect(typeof code).toBe('string');
      expect(code).toHaveLength(7);
    });

    it('should only contain URL-safe characters (A-Za-z0-9_-)', () => {
      const code = generateShortCode();
      expect(code).toMatch(/^[A-Za-z0-9_-]+$/);
    });

    it('should generate different codes on multiple calls (probabilistic uniqueness test)', () => {
      const codes = new Set<string>();
      const iterations = 100;

      for (let i = 0; i < iterations; i++) {
        codes.add(generateShortCode());
      }

      // Allow for extremely rare collisions (< 1 in 4.4 trillion per pair)
      // With 100 samples, collision probability is ~1.4e-9, but we use >= 99 to be safe
      expect(codes.size).toBeGreaterThanOrEqual(99);
    });

    it('should consistently generate 7-character codes across many iterations', () => {
      for (let i = 0; i < 50; i++) {
        const code = generateShortCode();
        expect(code).toHaveLength(7);
        expect(code).toMatch(/^[A-Za-z0-9_-]+$/);
      }
    });

    // Fix #4: Integration test validating SHORT_CODE_LENGTH constant usage
    it('should generate codes with length matching SHORT_CODE_LENGTH constant', () => {
      const code = generateShortCode();
      expect(code.length).toBe(SHORT_CODE_LENGTH);
    });

    // Fix #7: Performance benchmarking
    it('should generate codes in reasonable time (< 1ms per code)', () => {
      const start = performance.now();
      const iterations = 1000;

      for (let i = 0; i < iterations; i++) {
        generateShortCode();
      }

      const end = performance.now();
      const avgTimeMs = (end - start) / iterations;

      expect(avgTimeMs).toBeLessThan(1); // Each code generation should take < 1ms
    });
  });

  // Fix #3: Tests for isValidShortCode validation function
  describe('isValidShortCode', () => {
    it('should return true for valid short codes', () => {
      expect(isValidShortCode('aBc-123')).toBe(true);
      expect(isValidShortCode('1234567')).toBe(true);
      expect(isValidShortCode('ABC_XYZ')).toBe(true);
      expect(isValidShortCode('a-b_C9D')).toBe(true);
    });

    it('should return false for strings that are too short', () => {
      expect(isValidShortCode('abc')).toBe(false);
      expect(isValidShortCode('123456')).toBe(false); // 6 chars
      expect(isValidShortCode('')).toBe(false);
    });

    it('should return false for strings that are too long', () => {
      expect(isValidShortCode('12345678')).toBe(false); // 8 chars
      expect(isValidShortCode('abcdefghij')).toBe(false);
    });

    it('should return false for strings with invalid characters', () => {
      expect(isValidShortCode('abc@123')).toBe(false); // @ is invalid
      expect(isValidShortCode('abc 123')).toBe(false); // space is invalid
      expect(isValidShortCode('abc!123')).toBe(false); // ! is invalid
      expect(isValidShortCode('abc#123')).toBe(false); // # is invalid
    });

    it('should return false for non-string values', () => {
      expect(isValidShortCode(123)).toBe(false);
      expect(isValidShortCode(null)).toBe(false);
      expect(isValidShortCode(undefined)).toBe(false);
      expect(isValidShortCode({})).toBe(false);
      expect(isValidShortCode([])).toBe(false);
    });

    it('should validate codes generated by generateShortCode', () => {
      for (let i = 0; i < 20; i++) {
        const code = generateShortCode();
        expect(isValidShortCode(code)).toBe(true);
      }
    });
  });

  // Fix #6: Negative test cases and edge cases
  describe('generateShortCode - negative tests and edge cases', () => {
    it('should handle rapid successive calls without errors', () => {
      expect(() => {
        for (let i = 0; i < 1000; i++) {
          generateShortCode();
        }
      }).not.toThrow();
    });

    it('should not return empty strings', () => {
      for (let i = 0; i < 100; i++) {
        const code = generateShortCode();
        expect(code.length).toBeGreaterThan(0);
      }
    });

    it('should not return codes with whitespace', () => {
      for (let i = 0; i < 100; i++) {
        const code = generateShortCode();
        expect(code).not.toMatch(/\s/);
      }
    });

    it('should not return codes with special URL-unsafe characters', () => {
      const unsafeChars = /[^A-Za-z0-9_-]/;
      for (let i = 0; i < 100; i++) {
        const code = generateShortCode();
        expect(code).not.toMatch(unsafeChars);
      }
    });

    it('should maintain consistent output type across multiple calls', () => {
      for (let i = 0; i < 50; i++) {
        const code = generateShortCode();
        expect(typeof code).toBe('string');
      }
    });
  });
});
